version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandraorm-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraORM
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5

  scylladb:
    image: scylladb/scylla:5.2
    container_name: cassandraorm-scylla
    ports:
      - "9043:9042"
    command: --smp 1 --memory 1G --overprovisioned 1
    volumes:
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: cassandraorm-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - CASSANDRA_HOSTS=cassandra:9042
      - NODE_ENV=development
    command: bun run dev

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: cassandraorm-dashboard
    ports:
      - "3001:3001"
    depends_on:
      - cassandra
      - app
    environment:
      - API_URL=http://app:3000
      - CASSANDRA_HOSTS=cassandra:9042

volumes:
  cassandra_data:
  scylla_data:
