name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      cassandra:
        image: cassandra:4.1
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'describe keyspaces'"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 10

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Wait for Cassandra
      run: |
        echo "Waiting for Cassandra to be ready..."
        timeout 300 bash -c 'until nc -z localhost 9042; do echo "Waiting..."; sleep 5; done'
        echo "Cassandra is ready!"
        
    - name: Run tests
      run: npm test
